// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderService.proto

package com.yang.grpc.common.orderService;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
